apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: payment-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-service
        version: v1
    spec:
      containers:
        - name: payment-service
          image: 955065381857.dkr.ecr.cn-north-1.amazonaws.com.cn/payment-service:BUILD_VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
      imagePullSecrets:
        - name: new-secret
